### PR TITLE
feat route "echo"

### PR DESCRIPTION
**Pull request by iamdey**
basic route witch respond some JSON

### CODE REVIEW

**Comment by gdchamal** [comment]
This route must exist only on development platform. I'm thinkink about scan for this route only if we are in development mode (a configuration key in development.ini)

**Comment by iamdey** [comment]
I was thinking about a convention, not only for dev env. 

there is multiple use-cases we can think of with this convention: 

* a status page witch call `/echo`  on each http service (web, api, whatever intern plugin).
* check availability of a plugin
* ...?

**Comment by gdchamal** [comment]
A multipurpose API is not a design I want to consider.

- Simple echo service is for development only so must be activated only on such environment

- Plugin availability will be a specific route for any environment and will be considered later.

- Status page is a specific route for monitoring usage.

So ok to merge this feature, but must be activated in a declarative way for development purposes.

**Comment by iamdey** [comment]
I'm ok with your arguments. So this route has nothing to do here even for dev. I prefer to close this PR.

**Pull request closed without merging**
